service: auth0-custom-resource

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs14.x
  tracing:
    lambda: true

  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}

  memorySize: 256
  logRetentionInDays: 7

  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'xray:PutTraceSegments'
        - 'xray:PutTelemetryRecords'
      Resource:
        - '*'

custom:
  webpack:
    webpackConfig: webpack.config.js
    packager: 'npm'

package:
  individually: true

functions:
  auth0:
    handler: src/handler.auth0

resources:
  Outputs:
    ServiceToken:
      Value:
        'Fn::GetAtt': [Auth0LambdaFunction, Arn]
      Export:
        Name: '${self:service}:${self:provider.stage}:ServiceToken'
