service: aws-custom-resources

provider:
  name: aws

  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}

resources:
  Parameters:
    ApiTokenParameter:
      Type: String
      Default: ${env:CIRCLECI_API_TOKEN}
      NoEcho: true

  Resources:
    CircleCI:
      Type: 'Custom::CircleCI'
      Version: '1.0'
      Properties:
        ServiceToken:
          Fn::ImportValue: 'circleci-custom-resource:${self:provider.stage}:ServiceToken'
        ApiToken: { Ref: ApiTokenParameter }
        Owner: ${env:CIRCLECI_OWNER}
        Repo: ${env:CIRCLECI_REPO}
