service: circleci-aws-custom-resources-repo-setup

provider:
  name: aws

  stage: prod
  region: us-east-1

resources:
  Parameters:
    ApiTokenParameter:
      Type: String
      Default: ${env:CIRCLECI_API_TOKEN}
      NoEcho: true
    CoverallsRepoTokenParameter:
      Type: String
      Default: ${env:COVERALLS_REPO_TOKEN}
      NoEcho: true

  Resources:
    CircleCI:
      Type: 'Custom::CircleCI'
      Version: '1.0'
      Properties:
        ServiceToken:
          Fn::ImportValue: 'circleci-custom-resource:${self:provider.stage}:ServiceToken'
        ApiToken: { Ref: ApiTokenParameter }
        Owner: erezrokah
        Repo: aws-custom-resources
        EnvironmentVariables:
          - name: COVERALLS_SERVICE_NAME
            value: CircleCI
          - name: COVERALLS_REPO_TOKEN
            value: { Ref: CoverallsRepoTokenParameter }
