service: circleci-custom-resource

plugins:
  - serverless-webpack
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs10.x
  tracing:
    lambda: true

  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}

  memorySize: 256
  logRetentionInDays: 7

  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'xray:PutTraceSegments'
        - 'xray:PutTelemetryRecords'
      Resource:
        - '*'

    - Effect: 'Allow'
      Action:
        - 'iam:CreateUser'
        - 'iam:DeleteUser'
        - 'iam:AttachUserPolicy'
        - 'iam:DetachUserPolicy'
        - 'iam:ListAccessKeys'
        - 'iam:CreateAccessKey'
        - 'iam:DeleteAccessKey'

      Resource: 'arn:aws:iam::#{AWS::AccountId}:*'

custom:
  webpack:
    webpackConfig: webpack.config.js
    packager: 'yarn'

package:
  individually: true

functions:
  circleci:
    handler: src/handler.circleci

resources:
  Outputs:
    ServiceToken:
      Value:
        'Fn::GetAtt': [CircleciLambdaFunction, Arn]
      Export:
        Name: '${self:service}:${self:provider.stage}:ServiceToken'
